### ISSUE TITLE
Segment fault on run nfs2se

### ISSUE THREAD

**Issue by rdeprera** [zaps166/NFSIISE#81]
Everything ok on compiling. But when i run ...
```console
user@Debian11:~/Apps/NSSE$ ./nfs2se
Need For Speed II SE
  Wrapper v1.3.0
  Game    v1.1.2-cpp_r5
  OpenGL  2
Application closed with a signal: 11
Segmentation fault
```

Same with OpenGL 1
```console
user@Debian11:~/Apps/NSSE$ ./nfs2se
Need For Speed II SE
  Wrapper v1.3.0
  Game    v1.1.2
  OpenGL  1
Application closed with a signal: 11
Segmentation fault
```
I tried with:
- `debug`
- `release`
- `gl2`
- `cpp`
- and just with `./compile_nfs` or `./compile_nfs cpp`

Same result.

already thanks for attention

**Comment by zaps166** [comment]
Are your data from NFS 2 SE (not NFS 2)? Do you use script to make files lower case?

**Comment by rdeprera** [comment]
- My data is from NFS 2 SE
- Yes, was used the convert (very usefulscript)

## Solved

A lot of tests later ... **problem was solved** installing `GLX` 32-bot on
Debian: `sudo apt install libgl1-mesa-glx:i386`
[GLX is not necessary for compile but is a requirement to run the game](
https://github.com/zaps166/NFSIISE/pull/82)

Thanks for the attention Błażej



Em seg., 11 de abr. de 2022 às 09:58, Błażej Szczygieł <
***@***.***> escreveu:

**Comment by skipster1337** [comment]
> libgl1-mesa-glx:i386
What is the equivalent of this package on Arch?  I have `lib32-mesa` installed, and the dependency `libGL.so.1` is present in `/usr/lib32/`, however I still get segfaults trying to run the game. I installed it from the AUR trying both packages `nfs2se-git` and `nfs2se`, but nothing changed.

**Comment by zaps166** [comment]
What is the target machine? Is it x86 CPU or ARM CPU?

**Comment by skipster1337** [comment]
> What is the target machine? Is it x86 CPU or ARM CPU?

x86_64.
It's just an Intel Core 2 Duo running Arch.

**Comment by zaps166** [comment]
It works on my Manjaro (Arch derivative), I use `nfs2se-git` AUR package.

If you don't have 32-bit OpenGL, you'll see message of `./nfs2se: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory` or
![Screenshot_20220531_201457](https://user-images.githubusercontent.com/6239090/171256496-e3a0e26c-7475-4899-b6f2-5a161ed1a1d4.png)

You should install `lib32-libglvnd` and `lib32-mesa`, if you have NVIDIA, install also `lib32-nvidia-utils`.

If it doesn't help, make sure about lower case data (see README).

If it doesn't help, run GDB:
```
cd /opt/nfs2se
gdb ./nfs2se
```
and start by sending "r" command. When it crashes, run `bt` command and show me.

**Comment by skipster1337** [comment]
I have both `lib32-libglvnd` and `lib32-mesa` installed. This is an Intel iGPU, so `lib32-nvidia-utils` isn't needed.
I ran the commands in GDB. Here's the output (pardon my terminal transparency):
![Screenshot_2022-06-01_13-22-59](https://user-images.githubusercontent.com/91155070/171384037-e8763816-9336-4974-9f39-282842c31a8b.png)
I'm not much of a programmer but at first glance it looks to be an issue with SDL. Perhaps an update broke something?

**Comment by zaps166** [comment]
I tried on Intel GPU now - works without any problems.
Can you give me your data somehow? I can verify it.

**Comment by zaps166** [comment]
Your data is working to me. Crash is also possible when you don't have access to directories and/or subdirectories (but it shouldn't be inside SDL2...) - anyway, make sure you have permissions to at least read directories and files.
Second thing is to remove `$HOME/.nfs2se` and try again.

Are your 32-bit SDL2 and 32-bit OpenGL working correctly?

You can try also two other ways:
- download compiled binaries: https://github.com/zaps166/NFSIISE/releases
- use Steam's 32-bit libraries to run it (see https://github.com/zaps166/NFSIISE/issues/83#issuecomment-1128717674) - just add as "Non-Steam Game" and set compatibility to `Steam Linux Runtime`.

**Comment by skipster1337** [comment]
I used the precompiled binaries and put them in a folder inside my home directory (I should have read access to that), but it still crashes. The `~/.nfs2se` directory does not exist since the game never ran properly.  
I have no clue whether 32-bit SDL and OpenGL work correctly since I don't seem to have anything to test them with, but I don't see why they wouldn't be working as they are fully up to date...
I also tried running it with the Steam Linux Runtime but to no avail as it only shows the message "Failed to launch". I added it as a non-steam game by pointing it to the .desktop file present in the precompiled version.

**Comment by zaps166** [comment]
Old version was linked to this, new loads dynamically. Looks like SDL2 bug.

**Comment by zaps166** [comment]
I've added some optdepends into AUR package, but this game runs on my PC without lib32-libxrandr...

**Comment by skipster1337** [comment]
> I've added some optdepends into AUR package, but this game runs on my PC without lib32-libxrandr...
Strange, maybe it was required by the old version but not needed in the new one. After I installed all the dependencies, the latest version runs correctly. I am currently away so I can't check whether the latest version runs for me without libxrandr, so I suggest to leave it in as a dependency temporarily, until I can test further if you want.

**Comment by zaps166** [comment]
It will be nice to see what other dependencies it installed :smile: I've added `lib32-mesa` and `lib32-nvidia-utils` only so far.

**Comment by skipster1337** [comment]
libxrandr seems to depend on the following packages (according to the arch package repo)
![2022-06-12 21_04_46-Window](https://user-images.githubusercontent.com/91155070/173246969-bdf5dc14-4c7a-40f8-99bb-591a0e536a33.png)
:

**Comment by zaps166** [comment]
but I have to track dependencies of dependencies, etc... :smile: 

Removed `lib32-libxext`, I've got:
![Screenshot_20220612_203806](https://user-images.githubusercontent.com/6239090/173248239-746feb66-9949-4439-a30e-4b509b79b8ae.png)
 
Your crash were weird.

**Comment by rdeprera** [comment]
https://archlinux.org/packages/extra/x86_64/mesa/

Em ter., 31 de mai. de 2022 às 11:47, skipster1337 ***@***.***>
escreveu:
